Repository obi1kenobi/cargo-semver-checks, pull requests merged in 2024-03, with the labels that each got.

#679 rule: add `union_now_doc_hidden`
  src/lints/union_now_doc_hidden.ron
  src/query.rs
  test_crates/union_now_doc_hidden/new/Cargo.toml
  test_crates/union_now_doc_hidden/new/src/lib.rs
  test_crates/union_now_doc_hidden/old/Cargo.toml
  test_crates/union_now_doc_hidden/old/src/lib.rs
  test_outputs/union_now_doc_hidden.output.ron
Labels: A-lint, C-enhancement

#686 Raise compile-time and runtime MSRV to Rust 1.74.
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/config.rs
Labels: M-breaking-change

#721 Add `--color` setting to CLI.
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/lib.rs
  src/main.rs
  tests/color_config.rs
Labels: A-cli, C-enhancement
